<ul>
	<li><a href="panorama.php" title="panorama" <?php if($pagina == 'panorama'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Screening Prenatal</a></li>
	<li><a href="testdeembarazo.php" title="test de emabarazo" <?php if($pagina == 'testdeembarazo'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Prueba de embarazo</a></li>
	<li><a href="hipotiroidismo-hipertiroidismo.php" title="hipotiroidismo hipertiroidismo" <?php if($pagina == 'hipotiroidismo-hipertiroidismo'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Valoración de la función tiroidea</a></li>
	<li><a href="fertilidad.php" title="fertilidad" <?php if($pagina == 'fertilidad'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Valoración hormonal en la mujer</a></li>
	<li><a href="diabetes.php" title="diabetes" <?php if($pagina == 'diabetes'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Valoración & diagnóstico de la diabetes</a></li>
	<li><a href="insuficiencia-renal.php" title="insuficiencia renal" <?php if($pagina == 'insuficiencia-renal'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Valoración de la función renal</a></li>
	<li><a href="examen-de-orina.php" title="examen de orina" <?php if($pagina == 'examen-de-orina'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Examen de orina completa</a></li>
	<li><a href="infeccion-urinara.php" title="infección urinara" <?php if($pagina == 'infeccion-urinara'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Estudio de la infección urinaria</a></li>
	<li><a href="test-de-VIH-sida.php" title="test de VIH sida" <?php if($pagina == 'test-de-VIH-sida'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Pruebas vinculadas a la infección por VIH</a></li>
	<li><a href="hepatitis.php" title="hepatitis" <?php if($pagina == 'hepatitis'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Pruebas vinculadas a la hepatitis infecciosa A-B-C</a></li>
	<li><a href="infeccion-respiratoria.php" title="infeccion respiratoria" <?php if($pagina == 'infeccion-respiratoria'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Investigación de infecciones respiratorias</a></li>
	<li><a href="infeccion-gastrointestinal.php" title="infeccion gastrointestinal" <?php if($pagina == 'infeccion-gastrointestinal'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Investigación de infecciones gastrointestinales</a></li>
	<li><a href="meningitis.php" title="meningitis" <?php if($pagina == 'meningitis'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Panel de agentes de meningitis / Encefalitis (14 AG) PCR en LCRs</a></li>
	<li><a href="anticoagulantes.php" title="anticoagulantes" <?php if($pagina == 'anticoagulantes'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Valoración de la anticoagulación oral</a></li>
	<li><a href="enfermedad-celiaca.php" title="enfermedad celiaca" <?php if($pagina == 'celiaca'):?> class="current"<?php endif;?>><i class="fa fa-chevron-right" aria-hidden="true" style="margin-right:5px;"></i>Enfermedad Celíaca</a></li>
</ul>
